
    // DO NOT EDIT THIS FILE, it is auto-generated. It will be updated automatically.
    // All changes done to this file will be lost upon re-running the 'silence createapi' command.
    // If you want to create new API methods, define them in a new file.
    // Silence is a DEAL research team project, more info about us in https://deal.us.es

    'use_strict';
    
    import { BASE_URL, requestOptions } from './common.js';
    
    const topemployeesAPI_auto ={

    /**
    * Gets all topemployees
    */
    getAll:async function(){
        let response = await axios.get(`${BASE_URL}/topemployees`,requestOptions);
        return response.data;
    },
};

export {topemployeesAPI_auto};