// DO NOT EDIT THIS FILE, it is auto-generated. It will be updated automatically.
    // All changes done to this file will be lost upon re-running the 'silence createapi' command.
    // If you want to create new API methods, define them in a new file.

    'use_strict';
    
    import { BASE_URL, requestOptions } from './common.js';
    
    const topemployeesAPI_auto ={

    /**
    * Gets all topemployees
    */
    getAll: function(){
    return new Promise (function (resolve, reject) 
    {
        axios
            .get(`${BASE_URL}/topemployees`,requestOptions)
            .then(response => resolve(response.data))
            .catch(error => reject(error.response.data.message));
        });
    },
};

export {topemployeesAPI_auto};